### ISSUE TITLE
NTR: Spray underwater glider (BODCNVS-1099)

### ISSUE THREAD

**Issue by castelao** [nvs-vocabs/L06#2]
Hi @justinbuck @bodcmahe , could you help me? I'm not sure what is the procedure here to request two new 'generic' records for sub-surface gliders (https://vocab.nerc.ac.uk/collection/L06/current/27/):

- Scripps Institution of Oceanography Spray
- Scripps Institution of Oceanography Spray2

I followed the pattern of the other B76 within L06/27/. Does it look ok?

Thanks!

**Comment by bodcmahe** [comment]
Hi @castelao,
Many thanks for the request. These two terms will need to be added to the B76 collection, which describes individual platform models (we will then link the new model terms to the broader L06 concept 'sub-surface gliders' i.e. the platform category). This will then make the new model terms appear in the URL you provided above. In order for us to create the terms could you supply a definition for each please? The existing B76 term links in the URL can be looked at to get a feel for the detail needed (e.g. http://vocab.nerc.ac.uk/collection/B76/current/B7600025/). 
Any questions, just shout!
Thanks, Mark

**Comment by bodcmahe** [comment]
@louatbodc (for awareness)

**Comment by castelao** [comment]
Hi @bodcmahe , here are the definitions for Spray & Spray2

Spray:
The Spray underwater glider is an autonomous vehicle developed at the Instrument Development Group of Scripps Institution of Oceanography that profiles vertically by controlling buoyancy and moves horizontally on wings. Spray steers by changing its center of mass through the movement of internal heavy battery packs, communicates to shore using Iridium, and navigates with GPS. Spray carries sensors to measure a number of variables, including pressure, temperature, salinity, optical properties, dissolved oxygen, and velocity. In typical use, Spray cycles from the surface to 1000 m, traveling 6 km horizontally in 6 hours, with a horizontal velocity of about 0.25 m/s and a vertical velocity of roughly 0.1 m/s. GPS and Iridium antennas are in Spray’s wings, so when Spray is on the surface, it rolls 90° to navigate and communicate. During communication, Spray sends data to shore, and shore-based pilots can change mission parameters such as waypoints and dive depth. Typical deployment duration is 3-5 months, depending on sensor suite, stratification, dive depth, and profiling speed.


Spray2:
The Spray underwater glider is an autonomous vehicle developed at the Instrument Development Group of Scripps Institution of Oceanography that profiles vertically by controlling buoyancy and moves horizontally on wings. Spray steers by changing its center of mass through the movement of internal heavy battery packs, communicates to shore using Iridium, and navigates with GPS. Spray carries sensors to measure a number of variables, including pressure, temperature, salinity, optical properties, dissolved oxygen, and velocity. In typical use, Spray cycles from the surface to 1000 m, traveling 6 km horizontally in 6 hours, with a horizontal velocity of about 0.25 m/s and a vertical velocity of roughly 0.1 m/s. GPS and Iridium antennas are in Spray’s wings, so when Spray is on the surface, it rolls 90° to navigate and communicate. During communication, Spray sends data to shore, and shore-based pilots can change mission parameters such as waypoints and dive depth.


Thanks!

**Comment by louatbodc** [comment]
Terms are now created in B76:

B7600027 - Scripps Institution of Oceanography Spray glider
B7600028 - Scripps Institution of Oceanography Spray 2 glider

Linked to the following term in L06:
27 -	sub-surface gliders

Linked to the following term in B75:
ORG00134 - Scripps Institution of Oceanography

Linked to the following term in L35:
MAN0039 - Scripps Institution of Oceanography

Please note it may take up to 24 hours for newly published terms to appear on our web services.

Many thanks
Lou
