### ISSUE TITLE
NTR: mesocosm tank [BODCNVS-2317	]

### ISSUE THREAD

**Issue by timvdstap** [nvs-vocabs/L06#3]
### Term name (PrefLabel)

Mesocosm tank

### Definition

An indoor or outdoor tank that contains water. The tank has instruments attached to measure and control conditions to help evaluate how organisms or communities react to environmental changes, e.g. through deliberate manipulation of environmental variables such as increased temperature, carbon dioxide or pH levels. 

### Sources/references

https://en.wikipedia.org/wiki/Mesocosm

### Mapping to external terminologies

Not necessarily an external terminology but I think it should follow the definition of a [mesocosm bag](http://vocab.nerc.ac.uk/collection/L06/current/19/)

### ORCID
0000-0002-0053-0795

**Comment by JordanAthertonNOC** [comment]
Hi @timvdstap, apologies for the delay in picking this up. We will circulate this request among the relevant governance group for approval/comments and get back to you with a decision/new term hopefully at the end of next week.

**Comment by jakjonbodc** [comment]
Hi @timvdstap, your requested L06 term is now live on NVS:
mesocosm tank - An indoor or outdoor tank containing water, used to house an experimental system. Instruments attached to the tank are used to measure and control conditions to help evaluate how organisms or communities react to controlled environmental changes.
https://vocab.nerc.ac.uk/collection/L06/current/99/
