### ISSUE TITLE
NTR: Snowmobile [BODCNVS-2307]

### ISSUE THREAD

**Issue by felnne** [nvs-vocabs/L06#4]
### Term name (PrefLabel)

snowmobile

### Definition

A motorised vehicle designed for travel on snow.

### Sources/references

- https://en.wikipedia.org/wiki/Snowmobile

### ORCID

https://orcid.org/0000-0003-3703-3888

**Comment by felnne** [comment]
Hi @gwemon, is there a rough timeline for when this and #5 could be reviewed and hopefully accepted?

**Comment by JordanAthertonNOC** [comment]
Hi @felnne apologies we did not get back to you on this. We will pick this up now and hopefully have something for you at the end of next week. As this collection is governed by SeaDataNet, a proposal will need to be circulated among and approved by the governance group. I'll make sure that goes out today to get the ball rolling.

**Comment by jakjonbodc** [comment]
Hi @felnne, your requested L06 term is now live on NVS:
snowmobile - A motorised vehicle, designed with skis and tracks, for travel on snow.
https://vocab.nerc.ac.uk/collection/L06/current/98/
