### ISSUE TITLE
NTR: Snowcat [BODCNVS-2313]

### ISSUE THREAD

**Issue by felnne** [nvs-vocabs/L06#5]
### Term name (PrefLabel)

snowcat

### Definition

An enclosed-cab, truck-sized, fully tracked vehicle designed to travel over snow.

### Sources/references

- https://en.wikipedia.org/wiki/Snowcat

### ORCID

https://orcid.org/0000-0003-3703-3888

**Comment by felnne** [comment]
Ideally this would be considered alongside #4.

**Comment by jakjonbodc** [comment]
Hi @felnne, your requested L06 term is now live on NVS:
snowcat - An enclosed cab, truck-sized, fully tracked vehicle designed to travel over snow.
https://vocab.nerc.ac.uk/collection/L06/current/97/

**Comment by felnne** [comment]
Ah great thanks 👍.
